<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 1058909-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Tidy (vers Sep 26, 2004) Parsing "InputStream"]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>11</line>
    <column>-3</column>
    <text><![CDATA[trimming empty <div>]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>13</line>
    <column>8</column>
    <text><![CDATA[missing </div>]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>13</line>
    <column>8</column>
    <text><![CDATA[missing </div>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.0 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, no errors were found!]]></text>
  </message>
</messages>
