<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 1097062-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Tidy (vers Sep 26, 2004) Parsing "InputStream"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:dt"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:w"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:o"]]></text>
  </message>
  <message>
    <code>9</code>
    <level>1</level>
    <line>8</line>
    <column>10</column>
    <text><![CDATA[nested emphasis <span>]]></text>
  </message>
  <message>
    <code>9</code>
    <level>1</level>
    <line>8</line>
    <column>16</column>
    <text><![CDATA[nested emphasis <span>]]></text>
  </message>
  <message>
    <code>9</code>
    <level>1</level>
    <line>8</line>
    <column>54</column>
    <text><![CDATA[nested emphasis <span>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.0 Strict//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[6 warnings, no errors were found!]]></text>
  </message>
</messages>
