<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427675-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected <frame>]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>11</line>
    <column>2</column>
    <text><![CDATA[missing </noframes>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Frameset]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, no errors were found!
]]></text>
  </message>
</messages>
