<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427676-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>59</code>
    <level>2</level>
    <line>6</line>
    <column>15</column>
    <text><![CDATA[<spanstyle> unexpected or duplicate quote mark]]></text>
  </message>
  <message>
    <code>58</code>
    <level>2</level>
    <line>6</line>
    <column>15</column>
    <text><![CDATA[<spanstyle> attribute with missing trailing quote mark]]></text>
  </message>
  <message>
    <code>22</code>
    <level>3</level>
    <line>6</line>
    <column>15</column>
    <text><![CDATA[<spanstyle> is not recognized!]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>6</line>
    <column>15</column>
    <text><![CDATA[discarding unexpected <spanstyle>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>6</line>
    <column>44</column>
    <text><![CDATA[discarding unexpected </span>]]></text>
  </message>
  <message>
    <code>59</code>
    <level>2</level>
    <line>6</line>
    <column>53</column>
    <text><![CDATA[<a> unexpected or duplicate quote mark]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 2.0]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[6 warnings, 1 error were found!
]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

]]></text>
  </message>
</messages>
