<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427664-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> attribute "Ã1/2" has invalid value "xx"]]></text>
  </message>
  <message>
    <code>59</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> unexpected or duplicate quote mark]]></text>
  </message>
  <message>
    <code>59</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> unexpected or duplicate quote mark]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[<body> attribute "width" has invalid value "align="]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[5 warnings, no errors were found!
]]></text>
  </message>
</messages>
