<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427810-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>21</code>
    <level>2</level>
    <line>8</line>
    <column>1</column>
    <text><![CDATA[<blink> is not approved by W3C]]></text>
  </message>
  <message>
    <code>21</code>
    <level>2</level>
    <line>9</line>
    <column>2</column>
    <text><![CDATA[<wbr> is not approved by W3C]]></text>
  </message>
  <message>
    <code>21</code>
    <level>2</level>
    <line>10</line>
    <column>2</column>
    <text><![CDATA[<nobr> is not approved by W3C]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[4 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>4</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to control line wrapping.
Use "white-space: nowrap" to inhibit wrapping in place
of inserting <NOBR>...</NOBR> into the markup.
]]></text>
  </message>
</messages>
