<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427827-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>7</line>
    <column>21</column>
    <text><![CDATA[missing </a> before <a>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>6</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 3.2//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
