<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427840-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Tidy (vers 26-set-2004) Parsing "InputStream"]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>52</code>
    <level>3</level>
    <line>4</line>
    <column>1</column>
    <text><![CDATA[<span> missing '>' for end of tag]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>5</line>
    <column>2</column>
    <text><![CDATA[missing </span> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>5</line>
    <column>2</column>
    <text><![CDATA[trimming empty <span>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>5</line>
    <column>4</column>
    <text><![CDATA[inserting implicit <span>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>6</line>
    <column>-3</column>
    <text><![CDATA[discarding unexpected </span>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[5 warnings, 1 error were found!]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.]]></text>
  </message>
</messages>
