<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427822-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>7</line>
    <column>11</column>
    <text><![CDATA[missing </i> before </dd>]]></text>
  </message>
  <message>
    <code>12</code>
    <level>2</level>
    <line>7</line>
    <column>12</column>
    <text><![CDATA[missing <dd>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>7</line>
    <column>12</column>
    <text><![CDATA[discarding unexpected </i>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>8</line>
    <column>-3</column>
    <text><![CDATA[trimming empty <dd>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 2.0]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[5 warnings, no errors were found!
]]></text>
  </message>
</messages>
