<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427823-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>27</code>
    <level>2</level>
    <line>13</line>
    <column>1</column>
    <text><![CDATA[content occurs after end of body]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>13</line>
    <column>1</column>
    <text><![CDATA[replacing element <body> by <div>]]></text>
  </message>
  <message>
    <code>27</code>
    <level>2</level>
    <line>15</line>
    <column>-1</column>
    <text><![CDATA[content occurs after end of body]]></text>
  </message>
  <message>
    <code>26</code>
    <level>2</level>
    <line>18</line>
    <column>1</column>
    <text><![CDATA[plain text not inside 'noframes' element]]></text>
  </message>
  <message>
    <code>27</code>
    <level>2</level>
    <line>18</line>
    <column>1</column>
    <text><![CDATA[content occurs after end of body]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>19</line>
    <column>2</column>
    <text><![CDATA[missing </noframes>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Frameset]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[7 warnings, no errors were found!
]]></text>
  </message>
</messages>
