<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427838-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>11</line>
    <column>18</column>
    <text><![CDATA[missing </a> before <h3>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>11</line>
    <column>18</column>
    <text><![CDATA[trimming empty <p>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>11</line>
    <column>22</column>
    <text><![CDATA[inserting implicit <a>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>11</line>
    <column>32</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>24</code>
    <level>1</level>
    <line>16</line>
    <column>25</column>
    <text><![CDATA[<a> is probably intended as </a>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>17</line>
    <column>25</column>
    <text><![CDATA[missing </a> before <a>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>19</line>
    <column>1</column>
    <text><![CDATA[missing </a> before </body>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.0 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[7 warnings, no errors were found!
]]></text>
  </message>
</messages>
