<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 431956-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[no warnings or errors were found
]]></text>
  </message>
</messages>
