<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 433021-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[<p> attribute "align" has invalid value "fizzle"]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>10</line>
    <column>1</column>
    <text><![CDATA[<td> attribute "valign" has invalid value "center"]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>12</line>
    <column>1</column>
    <text><![CDATA[<td> attribute "valign" has invalid value "fuzzle"]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>14</line>
    <column>1</column>
    <text><![CDATA[<td> attribute "valign" has invalid value "fuzzle"]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>14</line>
    <column>1</column>
    <text><![CDATA[<td> attribute "align" has invalid value "fuzzle"]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[5 warnings, no errors were found!
]]></text>
  </message>
</messages>
