<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 433670-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>4</line>
    <column>9</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&apos"]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[1 warning, no errors were found!
]]></text>
  </message>
</messages>
