<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 435922-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>7</line>
    <column>3</column>
    <text><![CDATA[<input> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>7</line>
    <column>3</column>
    <text><![CDATA[inserting implicit <form>]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>12</line>
    <column>1</column>
    <text><![CDATA[missing </form>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, no errors were found!
]]></text>
  </message>
</messages>
