<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 438956-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[plain text isn't allowed in <head> elements]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>6</line>
    <column>2</column>
    <text><![CDATA[<body> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
