<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 463066-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>29</code>
    <level>2</level>
    <line>1</line>
    <column>11</column>
    <text><![CDATA[adjacent hyphens within comment]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:dt"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:w"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:o"]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>79</line>
    <column>1</column>
    <text><![CDATA[<style> lacks "type" attribute]]></text>
  </message>
  <message>
    <code>21</code>
    <level>2</level>
    <line>539</line>
    <column>62</column>
    <text><![CDATA[<o:p> is not approved by W3C]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>539</line>
    <column>63</column>
    <text><![CDATA[trimming empty <o:p>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>20</code>
    <level>2</level>
    <line>553</line>
    <column>1</column>
    <text><![CDATA[replacing element <p> by <li>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[20 warnings, no errors were found!
]]></text>
  </message>
</messages>
