<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 467865-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>24</code>
    <level>1</level>
    <line>6</line>
    <column>13</column>
    <text><![CDATA[<tt> is probably intended as </tt>]]></text>
  </message>
  <message>
    <code>10</code>
    <level>2</level>
    <line>6</line>
    <column>19</column>
    <text><![CDATA[replacing unexpected </tt> by </b>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>6</line>
    <column>45</column>
    <text><![CDATA[discarding unexpected </tt>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>6</line>
    <column>52</column>
    <text><![CDATA[discarding unexpected </b>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[4 warnings, no errors were found!
]]></text>
  </message>
</messages>
