<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 480843-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>6</line>
    <column>1</column>
    <text><![CDATA[<body> isn't allowed in <head> elements]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>8</line>
    <column>19</column>
    <text><![CDATA[<a> Anchor "newintro" already defined]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.1//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
