<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 500236-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>29</code>
    <level>2</level>
    <line>1</line>
    <column>11</column>
    <text><![CDATA[adjacent hyphens within comment]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[1 warning, no errors were found!
]]></text>
  </message>
</messages>
