<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 502348-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>50</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[br attribute "clear" lacks value]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>9</line>
    <column>1</column>
    <text><![CDATA[br attribute "clear" has invalid value "invalid"]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.0 Strict//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
