<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 504206-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>65</code>
    <level>2</level>
    <line>12</line>
    <column>1</column>
    <text><![CDATA[<form> discarding newline in URI reference]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>43</line>
    <column>1</column>
    <text><![CDATA[trimming empty <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>139</line>
    <column>1</column>
    <text><![CDATA[trimming empty <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>144</line>
    <column>1</column>
    <text><![CDATA[trimming empty <p>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>152</line>
    <column>1</column>
    <text><![CDATA[<form> lacks "action" attribute]]></text>
  </message>
  <message>
    <code>25</code>
    <level>2</level>
    <line>152</line>
    <column>1</column>
    <text><![CDATA[<form> shouldn't be nested]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>155</line>
    <column>1</column>
    <text><![CDATA[missing </form>]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>155</line>
    <column>1</column>
    <text><![CDATA[missing </form>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[9 warnings, no errors were found!
]]></text>
  </message>
</messages>
