<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 508245-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>17</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[inserting missing 'title' element]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[<table> lacks "summary" attribute]]></text>
  </message>
  <message>
    <code>52</code>
    <level>3</level>
    <line>4</line>
    <column>9</column>
    <text><![CDATA[<img> missing '>' for end of tag]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>4</line>
    <column>9</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>5</line>
    <column>16</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[5 warnings, 1 error were found!
]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

]]></text>
  </message>
  <message>
    <code>4</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The table summary attribute should be used to describe
the table structure. It is very helpful for people using
non-visual browsers. The scope and headers attributes for
table cells are useful for specifying which headers apply
to each table cell, enabling non-visual browsers to provide
a meaningful context for each cell.
]]></text>
  </message>
  <message>
    <code>1</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The alt attribute should be used to give a short description
of an image; longer descriptions should be given with the
longdesc attribute which takes a URL linked to the description.
These measures are needed for people using non-graphical browsers.
]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.
]]></text>
  </message>
</messages>
