<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 511679-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>39</code>
    <level>2</level>
    <line>4</line>
    <column>36</column>
    <text><![CDATA[unescaped <pre> in pre content]]></text>
  </message>
  <message>
    <code>39</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[unescaped <pre> in pre content]]></text>
  </message>
  <message>
    <code>39</code>
    <level>2</level>
    <line>6</line>
    <column>1</column>
    <text><![CDATA[unescaped <pre> in pre content]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[missing </pre>]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>7</line>
    <column>2</column>
    <text><![CDATA[missing </table>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[6 warnings, no errors were found!
]]></text>
  </message>
</messages>
