<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 516370-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>71</code>
    <level>2</level>
    <line>10</line>
    <column>1</column>
    <text><![CDATA[ID "<h2>" uses XML ID syntax]]></text>
  </message>
  <message>
    <code>71</code>
    <level>2</level>
    <line>11</line>
    <column>1</column>
    <text><![CDATA[ID "<h2>" uses XML ID syntax]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>13</line>
    <column>1</column>
    <text><![CDATA[<h2> attribute "id" has invalid value ".InvalidID1"]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>14</line>
    <column>1</column>
    <text><![CDATA[<h2> attribute "id" has invalid value "2InvalidID2"]]></text>
  </message>
  <message>
    <code>50</code>
    <level>2</level>
    <line>15</line>
    <column>1</column>
    <text><![CDATA[<h2> attribute "id" lacks value]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.1//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[5 warnings, no errors were found!
]]></text>
  </message>
</messages>
