<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 532535-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>21</code>
    <level>2</level>
    <line>7</line>
    <column>57</column>
    <text><![CDATA[<o:p> is not approved by W3C]]></text>
  </message>
  <message>
    <code>28</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[html doctype doesn't match content]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
