<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 574158-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>7</line>
    <column>16</column>
    <text><![CDATA[missing </font> before <div>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>7</line>
    <column>16</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>7</line>
    <column>36</column>
    <text><![CDATA[inserting implicit <font>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.0 Strict//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>8</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to specify the font and
properties such as its size and color. This will reduce
the size of HTML files and make them easier to maintain
compared with using <FONT> elements.
]]></text>
  </message>
</messages>
