<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 588061-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>14</line>
    <column>30</column>
    <text><![CDATA[missing </strong> before <h1>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>14</line>
    <column>30</column>
    <text><![CDATA[trimming empty <strong>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>14</line>
    <column>36</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>18</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>20</line>
    <column>3</column>
    <text><![CDATA[missing </strong> before <center>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>20</line>
    <column>16</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>22</line>
    <column>3</column>
    <text><![CDATA[missing </strong> before <h1>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>23</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>25</line>
    <column>190</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>25</line>
    <column>190</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>43</line>
    <column>248</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>10</code>
    <level>2</level>
    <line>46</line>
    <column>430</column>
    <text><![CDATA[replacing unexpected </font> by </strong>]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>66</line>
    <column>202</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&city"]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>73</line>
    <column>1</column>
    <text><![CDATA[missing </strong> before <h2>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>73</line>
    <column>1</column>
    <text><![CDATA[missing </h3> before <h2>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>74</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>74</line>
    <column>513</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>74</line>
    <column>513</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>102</line>
    <column>202</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>102</line>
    <column>501</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>102</line>
    <column>501</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>106</line>
    <column>198</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>106</line>
    <column>495</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>106</line>
    <column>495</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>110</line>
    <column>194</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>110</line>
    <column>489</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>110</line>
    <column>489</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>114</line>
    <column>190</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>114</line>
    <column>477</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>114</line>
    <column>477</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>118</line>
    <column>186</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>118</line>
    <column>471</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>118</line>
    <column>471</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>122</line>
    <column>174</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>122</line>
    <column>441</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>122</line>
    <column>441</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>126</line>
    <column>170</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>126</line>
    <column>449</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>126</line>
    <column>449</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>130</line>
    <column>174</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>130</line>
    <column>453</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>130</line>
    <column>453</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>134</line>
    <column>174</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>134</line>
    <column>459</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>134</line>
    <column>459</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>138</line>
    <column>176</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>138</line>
    <column>461</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>138</line>
    <column>461</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>142</line>
    <column>176</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>142</line>
    <column>461</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>142</line>
    <column>461</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>168</line>
    <column>258</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>168</line>
    <column>547</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>168</line>
    <column>547</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>188</line>
    <column>144</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>196</line>
    <column>302</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>200</line>
    <column>348</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>200</line>
    <column>665</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>200</line>
    <column>665</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>216</line>
    <column>172</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>240</line>
    <column>126</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>248</line>
    <column>181</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>248</line>
    <column>546</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>248</line>
    <column>546</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>296</line>
    <column>264</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>300</line>
    <column>345</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>300</line>
    <column>404</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>314</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>318</line>
    <column>3</column>
    <text><![CDATA[missing </strong> before <center>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>318</line>
    <column>16</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>318</line>
    <column>16</column>
    <text><![CDATA[missing </strong> before <h1>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>318</line>
    <column>16</column>
    <text><![CDATA[trimming empty <strong>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>318</line>
    <column>22</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>328</line>
    <column>118</column>
    <text><![CDATA[missing </a> before </h1>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>328</line>
    <column>127</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>339</line>
    <column>1</column>
    <text><![CDATA[<center> isn't allowed in <h3> elements]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>339</line>
    <column>16</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>339</line>
    <column>120</column>
    <text><![CDATA[discarding unexpected </center>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>341</line>
    <column>1</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>345</line>
    <column>3</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>349</line>
    <column>3</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>353</line>
    <column>3</column>
    <text><![CDATA[<center> isn't allowed in <h3> elements]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>353</line>
    <column>16</column>
    <text><![CDATA[missing </h3> before <h1>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>353</line>
    <column>166</column>
    <text><![CDATA[discarding unexpected </center>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>363</line>
    <column>527</column>
    <text><![CDATA[discarding unexpected </h3>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>371</line>
    <column>154</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>383</line>
    <column>99</column>
    <text><![CDATA[missing </a> before </h2>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>383</line>
    <column>102</column>
    <text><![CDATA[discarding unexpected </strong>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>383</line>
    <column>119</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>388</line>
    <column>1</column>
    <text><![CDATA[<table> lacks "summary" attribute]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>414</line>
    <column>150</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&font"]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>414</line>
    <column>181</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&base"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>414</line>
    <column>181</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>424</line>
    <column>3</column>
    <text><![CDATA[discarding unexpected </strong>]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>3</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Panic - tree has lost its integrity
]]></text>
  </message>
</messages>
