<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 610244-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>13</line>
    <column>1</column>
    <text><![CDATA[<script> lacks "type" attribute]]></text>
  </message>
  <message>
    <code>32</code>
    <level>2</level>
    <line>39</line>
    <column>108</column>
    <text><![CDATA['<' + '/' + letter not allowed here]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>39</line>
    <column>114</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>39</line>
    <column>115</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&parent.frames.length"]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>43</line>
    <column>30</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>43</line>
    <column>31</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&d.all"]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>43</line>
    <column>92</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>43</line>
    <column>93</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&i"]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>43</line>
    <column>93</column>
    <text><![CDATA[plain text isn't allowed in <head> elements]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>43</line>
    <column>97</column>
    <text><![CDATA[unknown attribute "i++)"]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>45</line>
    <column>24</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>45</line>
    <column>25</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&d.layers"]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>45</line>
    <column>42</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>45</line>
    <column>43</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&i"]]></text>
  </message>
  <message>
    <code>52</code>
    <level>3</level>
    <line>45</line>
    <column>43</column>
    <text><![CDATA[<d.forms.length> missing '>' for end of tag]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>45</line>
    <column>43</column>
    <text><![CDATA[<d.forms.length> attribute "for(i" has invalid value "0;!x&&d.layers&&i"]]></text>
  </message>
  <message>
    <code>22</code>
    <level>3</level>
    <line>45</line>
    <column>43</column>
    <text><![CDATA[<d.forms.length> is not recognized!]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>45</line>
    <column>43</column>
    <text><![CDATA[discarding unexpected <d.forms.length>]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[unknown attribute "i++)"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[unknown attribute "x;"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[unknown attribute "}"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[unknown attribute "mm_swapimage()"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[unknown attribute "{"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[unknown attribute "//v3.0"]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[<d.layers.length> attribute "i,j" has invalid value "0,x,a=MM_swapImage.arguments;"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[unknown attribute "array;"]]></text>
  </message>
  <message>
    <code>52</code>
    <level>3</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[<d.layers.length> missing '>' for end of tag]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[<d.layers.length> attribute "for(i" has invalid value "0;i"]]></text>
  </message>
  <message>
    <code>22</code>
    <level>3</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[<d.layers.length> is not recognized!]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>45</line>
    <column>46</column>
    <text><![CDATA[discarding unexpected <d.layers.length>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>61</line>
    <column>3</column>
    <text><![CDATA[discarding unexpected </script>]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>63</line>
    <column>3</column>
    <text><![CDATA[</head> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>65</line>
    <column>3</column>
    <text><![CDATA[<body> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>70</line>
    <column>5</column>
    <text><![CDATA[trimming empty <center>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>72</line>
    <column>284</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>72</line>
    <column>717</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>72</line>
    <column>933</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>72</line>
    <column>1382</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>72</line>
    <column>1821</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>74</line>
    <column>49</column>
    <text><![CDATA[<img> attribute "align" has invalid value "abscenter"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>74</line>
    <column>49</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>74</line>
    <column>434</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>74</line>
    <column>434</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>75</line>
    <column>15</column>
    <text><![CDATA[<img> attribute "align" has invalid value "abscenter"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>15</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>75</line>
    <column>366</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>366</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>75</line>
    <column>585</column>
    <text><![CDATA[<img> attribute "align" has invalid value "abscenter"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>585</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>75</line>
    <column>938</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>938</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>75</line>
    <column>1141</column>
    <text><![CDATA[<img> attribute "align" has invalid value "abscenter"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>1141</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>75</line>
    <column>1222</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>1222</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>51</code>
    <level>2</level>
    <line>75</line>
    <column>1431</column>
    <text><![CDATA[<img> attribute "align" has invalid value "abscenter"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>1431</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>75</line>
    <column>1803</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>75</line>
    <column>1803</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>80</line>
    <column>1</column>
    <text><![CDATA[trimming empty <center>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>82</line>
    <column>9</column>
    <text><![CDATA[<table> lacks "summary" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>84</line>
    <column>107</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>84</line>
    <column>107</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>84</line>
    <column>257</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>86</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>86</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>88</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>88</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>90</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>90</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>90</line>
    <column>176</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>92</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>92</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>92</line>
    <column>176</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>94</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>94</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>94</line>
    <column>176</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>96</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>96</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>96</line>
    <column>176</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>98</line>
    <column>102</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>98</line>
    <column>102</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>99</line>
    <column>67</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>99</line>
    <column>67</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>101</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>101</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>103</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>103</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>105</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>105</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>106</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>106</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>107</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>107</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>108</line>
    <column>102</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>108</line>
    <column>102</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>110</line>
    <column>49</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>110</line>
    <column>49</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>112</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>112</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>113</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>113</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>113</line>
    <column>176</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>115</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>115</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>116</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>116</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>54</code>
    <level>2</level>
    <line>118</line>
    <column>27</column>
    <text><![CDATA[<img> proprietary attribute value "absmiddle"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>118</line>
    <column>27</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>123</line>
    <column>-3</column>
    <text><![CDATA[trimming empty <dl>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>128</line>
    <column>1</column>
    <text><![CDATA[<table> lacks "summary" attribute]]></text>
  </message>
  <message>
    <code>12</code>
    <level>2</level>
    <line>186</line>
    <column>5</column>
    <text><![CDATA[missing <dd>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>187</line>
    <column>117</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>189</line>
    <column>89</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>189</line>
    <column>96</column>
    <text><![CDATA[trimming empty <div>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>190</line>
    <column>82</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>190</line>
    <column>94</column>
    <text><![CDATA[trimming empty <div>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>198</line>
    <column>1</column>
    <text><![CDATA[<table> lacks "summary" attribute]]></text>
  </message>
  <message>
    <code>53</code>
    <level>2</level>
    <line>198</line>
    <column>1</column>
    <text><![CDATA[<table> proprietary attribute "height"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>202</line>
    <column>102</column>
    <text><![CDATA[unknown attribute "v:shapes"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>202</line>
    <column>102</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>22</code>
    <level>3</level>
    <line>204</line>
    <column>148</column>
    <text><![CDATA[<o:p> is not recognized!]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>204</line>
    <column>148</column>
    <text><![CDATA[discarding unexpected <o:p>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>204</line>
    <column>152</column>
    <text><![CDATA[discarding unexpected </o:p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>204</line>
    <column>162</column>
    <text><![CDATA[trimming empty <span>]]></text>
  </message>
  <message>
    <code>22</code>
    <level>3</level>
    <line>206</line>
    <column>148</column>
    <text><![CDATA[<o:p> is not recognized!]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>206</line>
    <column>148</column>
    <text><![CDATA[discarding unexpected <o:p>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>206</line>
    <column>152</column>
    <text><![CDATA[discarding unexpected </o:p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>206</line>
    <column>162</column>
    <text><![CDATA[trimming empty <span>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[206 warnings, 10 errors were found!
]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

]]></text>
  </message>
  <message>
    <code>76</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[It is unlikely that vendor-specific, system-dependent encodings
work widely enough on the World Wide Web; you should avoid using the 
specified character encoding, instead you are recommended to
use named entities, e.g. &trade;.
]]></text>
  </message>
  <message>
    <code>77</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
even if they were, they would likely be unprintable control characters.
Tidy assumed you wanted to refer to a character with the same byte value in the 
specified encoding and replaced that reference with the Unicode equivalent.
]]></text>
  </message>
  <message>
    <code>78</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-8 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-8 in Annex D of ISO/IEC 10646-1:2000 also
allows for the use of five- and six-byte sequences to encode
characters that are outside the range of the Unicode character set;
those five- and six-byte sequences are illegal for the use of
UTF-8 as a transformation of Unicode characters. ISO/IEC 10646
does not allow mapping of unpaired surrogates, nor U+FFFE and U+FFFF
(but it does allow other noncharacters). For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html
]]></text>
  </message>
  <message>
    <code>79</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-16 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-16 in Annex C of ISO/IEC 10646-1:2000 does not allow the
mapping of unpaired surrogates. For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html
]]></text>
  </message>
  <message>
    <code>81</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[URIs must be properly escaped, they must not contain unescaped
characters below U+0021 including the space character and not
above U+007E. Tidy escapes the URI for you as recommended by
HTML 4.01 section B.2.1 and XML 1.0 section 4.2.2. Some user agents
use another algorithm to escape such URIs and some server-sided
scripts depend on that. If you want to depend on that, you must
escape the URI by your own. For more information please refer to
http://www.w3.org/International/O-URL-and-ident.html
]]></text>
  </message>
  <message>
    <code>4</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[The table summary attribute should be used to describe
the table structure. It is very helpful for people using
non-visual browsers. The scope and headers attributes for
table cells are useful for specifying which headers apply
to each table cell, enabling non-visual browsers to provide
a meaningful context for each cell.
]]></text>
  </message>
  <message>
    <code>1</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[The alt attribute should be used to give a short description
of an image; longer descriptions should be given with the
longdesc attribute which takes a URL linked to the description.
These measures are needed for people using non-graphical browsers.
]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.
]]></text>
  </message>
  <message>
    <code>8</code>
    <level>0</level>
    <line>1037</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to specify the font and
properties such as its size and color. This will reduce
the size of HTML files and make them easier to maintain
compared with using <FONT> elements.
]]></text>
  </message>
</messages>
