<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 680664-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>29</code>
    <level>2</level>
    <line>13</line>
    <column>38</column>
    <text><![CDATA[adjacent hyphens within comment]]></text>
  </message>
  <message>
    <code>6</code>
    <level>2</level>
    <line>18</line>
    <column>1</column>
    <text><![CDATA[missing </pre>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.0 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
