<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 943559-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>12</code>
    <level>2</level>
    <line>10</line>
    <column>7</column>
    <text><![CDATA[missing <td>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>11</line>
    <column>13</column>
    <text><![CDATA[discarding unexpected <td>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>11</line>
    <column>20</column>
    <text><![CDATA[missing </form> before </td>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>3</level>
    <line>12</line>
    <column>7</column>
    <text><![CDATA[discarding unexpected </form>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.0 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, 1 error were found!
]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

]]></text>
  </message>
  <message>
    <code>113</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You may need to move one or both of the <form> and </form>
tags. HTML elements should be properly nested and form elements
are no exception. For instance you should not place the <form>
in one table cell and the </form> in another. If the <form> is
placed before a table, the </form> cannot be placed inside the
table! Note that one form can't be nested inside another!
]]></text>
  </message>
</messages>
