<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 1392829-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Tidy (vers 26-set-2004) Parsing "InputStream"]]></text>
  </message>
  <message>
    <code>50</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[<font> attribute "size" lacks value]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>9</line>
    <column>6</column>
    <text><![CDATA[<script> lacks "type" attribute]]></text>
  </message>
  <message>
    <code>32</code>
    <level>2</level>
    <line>12</line>
    <column>52</column>
    <text><![CDATA['<' + '/' + letter not allowed here]]></text>
  </message>
  <message>
    <code>10</code>
    <level>2</level>
    <line>14</line>
    <column>1</column>
    <text><![CDATA[replacing unexpected </script> by </b>]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>16</line>
    <column>2</column>
    <text><![CDATA[unknown attribute "3"]]></text>
  </message>
  <message>
    <code>50</code>
    <level>2</level>
    <line>16</line>
    <column>2</column>
    <text><![CDATA[<font> attribute "size" lacks value]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD XHTML 1.0 Strict//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[6 warnings, no errors were found!]]></text>
  </message>
  <message>
    <code>8</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to specify the font and
properties such as its size and color. This will reduce
the size of HTML files and make them easier to maintain
compared with using <FONT> elements.]]></text>
  </message>
</messages>
