<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 1416185-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Tidy (vers 26-set-2004) Parsing "InputStream"]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>9</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected <frame>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Frameset]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!]]></text>
  </message>
  <message>
    <code>16</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Pages designed using frames presents problems for
people who are either blind or using a browser that
doesn't support frames. A frames-based page should always
include an alternative layout inside a NOFRAMES element.]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.]]></text>
  </message>
</messages>
