<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 426885-->
<messages>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[<dt> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <dl>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>7</line>
    <column>5</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>8</line>
    <column>5</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>8</line>
    <column>41</column>
    <text><![CDATA[<hr> isn't allowed in <dt> elements]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>8</line>
    <column>41</column>
    <text><![CDATA[trimming empty <dt>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>9</line>
    <column>9</column>
    <text><![CDATA[missing </center> before <h1>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>9</line>
    <column>9</column>
    <text><![CDATA[trimming empty <center>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>9</line>
    <column>9</column>
    <text><![CDATA[trimming empty <dl>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>9</line>
    <column>23</column>
    <text><![CDATA[discarding unexpected </center>]]></text>
  </message>
  <message>
    <code>12</code>
    <level>2</level>
    <line>11</line>
    <column>1</column>
    <text><![CDATA[missing <li>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>11</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <dl>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>11</line>
    <column>5</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>12</line>
    <column>5</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>12</line>
    <column>41</column>
    <text><![CDATA[<hr> isn't allowed in <dt> elements]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>12</line>
    <column>41</column>
    <text><![CDATA[trimming empty <dt>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>13</line>
    <column>-3</column>
    <text><![CDATA[missing </dl> before </ul>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[18 warnings, no errors were found!]]></text>
  </message>
  <message>
    <code>1</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The alt attribute should be used to give a short description
of an image; longer descriptions should be given with the
longdesc attribute which takes a URL linked to the description.
These measures are needed for people using non-graphical browsers.]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.]]></text>
  </message>
</messages>
