<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427671-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>5</column>
    <text><![CDATA[discarding unexpected <frame>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>22</column>
    <text><![CDATA[discarding unexpected </frame>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>9</line>
    <column>5</column>
    <text><![CDATA[discarding unexpected <frameset>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>9</line>
    <column>28</column>
    <text><![CDATA[discarding unexpected </frameset>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>10</line>
    <column>5</column>
    <text><![CDATA[discarding unexpected <optgroup>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>10</line>
    <column>28</column>
    <text><![CDATA[discarding unexpected </optgroup>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>11</line>
    <column>5</column>
    <text><![CDATA[discarding unexpected <option>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>11</line>
    <column>24</column>
    <text><![CDATA[discarding unexpected </option>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[9 warnings, no errors were found!
]]></text>
  </message>
</messages>
