<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427833-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>10</line>
    <column>26</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&#X3e"]]></text>
  </message>
  <message>
    <code>28</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[html doctype doesn't match content]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
