<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 427819-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>6</line>
    <column>1</column>
    <text><![CDATA[<form> lacks "action" attribute]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>26</column>
    <text><![CDATA[discarding unexpected <font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>46</column>
    <text><![CDATA[discarding unexpected </font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>12</line>
    <column>26</column>
    <text><![CDATA[discarding unexpected <font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>12</line>
    <column>45</column>
    <text><![CDATA[discarding unexpected </font>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[6 warnings, no errors were found!
]]></text>
  </message>
</messages>
