<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 433672-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>6</line>
    <column>15</column>
    <text><![CDATA[missing </a> before <h2>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>6</line>
    <column>19</column>
    <text><![CDATA[inserting implicit <a>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>6</line>
    <column>35</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>9</line>
    <column>16</column>
    <text><![CDATA[missing </a> before <center>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>9</line>
    <column>62</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[6 warnings, no errors were found!
]]></text>
  </message>
</messages>
