<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 433856-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>29</code>
    <level>2</level>
    <line>2</line>
    <column>11</column>
    <text><![CDATA[adjacent hyphens within comment]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>10</line>
    <column>33</column>
    <text><![CDATA[missing </font> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>10</line>
    <column>33</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>10</line>
    <column>33</column>
    <text><![CDATA[missing </u> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>10</line>
    <column>33</column>
    <text><![CDATA[trimming empty <u>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>10</line>
    <column>33</column>
    <text><![CDATA[missing </b> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>10</line>
    <column>33</column>
    <text><![CDATA[trimming empty <b>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>10</line>
    <column>36</column>
    <text><![CDATA[inserting implicit <b>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>10</line>
    <column>36</column>
    <text><![CDATA[inserting implicit <u>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>10</line>
    <column>36</column>
    <text><![CDATA[inserting implicit <font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>11</line>
    <column>-3</column>
    <text><![CDATA[discarding unexpected </b>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>11</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected </u>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>11</line>
    <column>5</column>
    <text><![CDATA[discarding unexpected </font>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>12</line>
    <column>1</column>
    <text><![CDATA[missing </font> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>12</line>
    <column>1</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>12</line>
    <column>4</column>
    <text><![CDATA[inserting implicit <font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>13</line>
    <column>-3</column>
    <text><![CDATA[discarding unexpected </font>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[18 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>8</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to specify the font and
properties such as its size and color. This will reduce
the size of HTML files and make them easier to maintain
compared with using <FONT> elements.
]]></text>
  </message>
</messages>
