<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 434100-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>13</code>
    <level>3</level>
    <line>13</line>
    <column>-3</column>
    <text><![CDATA[unexpected </head> in <link>]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[no warnings, 1 error were found!
]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

]]></text>
  </message>
</messages>
