<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 434940b-->
<messages>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[no warnings or errors were found]]></text>
  </message>
</messages>
