<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 435903-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>4</line>
    <column>5</column>
    <text><![CDATA[<table> lacks "summary" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>10</line>
    <column>9</column>
    <text><![CDATA[<script> lacks "type" attribute]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>10</line>
    <column>9</column>
    <text><![CDATA[<script> isn't allowed in <tr> elements]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>17</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected </table>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>18</line>
    <column>-1</column>
    <text><![CDATA[trimming empty <tr>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>18</line>
    <column>-1</column>
    <text><![CDATA[missing </table> before </body>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[7 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>4</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The table summary attribute should be used to describe
the table structure. It is very helpful for people using
non-visual browsers. The scope and headers attributes for
table cells are useful for specifying which headers apply
to each table cell, enabling non-visual browsers to provide
a meaningful context for each cell.
]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.
]]></text>
  </message>
</messages>
