<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 470688-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>10</code>
    <level>2</level>
    <line>8</line>
    <column>6</column>
    <text><![CDATA[replacing unexpected </i> by </u>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>8</line>
    <column>6</column>
    <text><![CDATA[trimming empty <u>]]></text>
  </message>
  <message>
    <code>24</code>
    <level>1</level>
    <line>8</line>
    <column>30</column>
    <text><![CDATA[<i> is probably intended as </i>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>28</column>
    <text><![CDATA[discarding unexpected </u>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>8</line>
    <column>32</column>
    <text><![CDATA[discarding unexpected </i>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[5 warnings, no errors were found!
]]></text>
  </message>
</messages>
