<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 505770-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>4</line>
    <column>29</column>
    <text><![CDATA[missing </title> before <option>]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>4</line>
    <column>29</column>
    <text><![CDATA[<option> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>4</line>
    <column>57</column>
    <text><![CDATA[discarding unexpected </title>]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>5</line>
    <column>1</column>
    <text><![CDATA[</head> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>6</line>
    <column>2</column>
    <text><![CDATA[<body> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>8</line>
    <column>2</column>
    <text><![CDATA[<form> lacks "action" attribute]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>29</line>
    <column>37</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>30</line>
    <column>37</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[9 warnings, no errors were found!
]]></text>
  </message>
</messages>
