<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 508936-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 3.2]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[1 warning, no errors were found!
]]></text>
  </message>
  <message>
    <code>8</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to specify the font and
properties such as its size and color. This will reduce
the size of HTML files and make them easier to maintain
compared with using <FONT> elements.
]]></text>
  </message>
</messages>
