<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 538536-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>27</code>
    <level>2</level>
    <line>8</line>
    <column>-3</column>
    <text><![CDATA[content occurs after end of body]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>9</line>
    <column>-3</column>
    <text><![CDATA[discarding unexpected </html>]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.01//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[2 warnings, no errors were found!
]]></text>
  </message>
</messages>
