<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 540571-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>6</line>
    <column>19</column>
    <text><![CDATA[missing </font> before <h1>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>6</line>
    <column>19</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>6</line>
    <column>23</column>
    <text><![CDATA[inserting implicit <font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>6</line>
    <column>35</column>
    <text><![CDATA[discarding unexpected </font>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>10</line>
    <column>19</column>
    <text><![CDATA[missing </span> before <h1>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>10</line>
    <column>19</column>
    <text><![CDATA[trimming empty <span>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>10</line>
    <column>35</column>
    <text><![CDATA[discarding unexpected </span>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[8 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>8</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to specify the font and
properties such as its size and color. This will reduce
the size of HTML files and make them easier to maintain
compared with using <FONT> elements.
]]></text>
  </message>
</messages>
