<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 566542-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>4</line>
    <column>1</column>
    <text><![CDATA[<li> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>4</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <ul>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>4</line>
    <column>5</column>
    <text><![CDATA[trimming empty <li>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>4</line>
    <column>5</column>
    <text><![CDATA[missing </ul> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>4</line>
    <column>5</column>
    <text><![CDATA[trimming empty <ul>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>6</line>
    <column>7</column>
    <text><![CDATA[missing </b> before <p>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <b>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[missing </b> before <li>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[trimming empty <b>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[trimming empty <p>]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[<li> isn't allowed in <body> elements]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>7</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <ul>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>7</line>
    <column>5</column>
    <text><![CDATA[inserting implicit <b>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>7</line>
    <column>5</column>
    <text><![CDATA[missing </b> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>7</line>
    <column>5</column>
    <text><![CDATA[trimming empty <b>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>7</line>
    <column>5</column>
    <text><![CDATA[trimming empty <li>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>7</line>
    <column>5</column>
    <text><![CDATA[missing </ul> before <p>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>7</line>
    <column>5</column>
    <text><![CDATA[trimming empty <ul>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>7</line>
    <column>8</column>
    <text><![CDATA[inserting implicit <b>]]></text>
  </message>
  <message>
    <code>24</code>
    <level>1</level>
    <line>7</line>
    <column>40</column>
    <text><![CDATA[<b> is probably intended as </b>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>9</line>
    <column>1</column>
    <text><![CDATA[trimming empty <p>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 2.0]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[22 warnings, no errors were found!
]]></text>
  </message>
</messages>
