<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 570027-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[Tidy (vers 26-set-2004) Parsing "InputStream"]]></text>
  </message>
  <message>
    <code>29</code>
    <level>2</level>
    <line>1</line>
    <column>11</column>
    <text><![CDATA[adjacent hyphens within comment]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:w"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:o"]]></text>
  </message>
  <message>
    <code>48</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[unknown attribute "xmlns:v"]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>9</code>
    <level>1</level>
    <line>21</line>
    <column>9</column>
    <text><![CDATA[nested emphasis <span>]]></text>
  </message>
  <message>
    <code>1</code>
    <level>2</level>
    <line>22</line>
    <column>33</column>
    <text><![CDATA[Warning: entity "&nbsp" doesn't end in ';']]></text>
  </message>
  <message>
    <code>65</code>
    <level>2</level>
    <line>27</line>
    <column>44</column>
    <text><![CDATA[<a> discarding newline in URI reference]]></text>
  </message>
  <message>
    <code>21</code>
    <level>2</level>
    <line>29</line>
    <column>42</column>
    <text><![CDATA[<o:p> is not approved by W3C]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[9 warnings, no errors were found!]]></text>
  </message>
</messages>
