<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 588061-->
<messages>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>14</line>
    <column>17</column>
    <text><![CDATA[missing </strong> before <h1>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>14</line>
    <column>17</column>
    <text><![CDATA[trimming empty <strong>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>14</line>
    <column>21</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>18</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>20</line>
    <column>2</column>
    <text><![CDATA[missing </strong> before <center>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>20</line>
    <column>9</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>22</line>
    <column>2</column>
    <text><![CDATA[missing </strong> before <h1>]]></text>
  </message>
  <message>
    <code>15</code>
    <level>2</level>
    <line>23</line>
    <column>1</column>
    <text><![CDATA[inserting implicit <strong>]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>25</line>
    <column>96</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>25</line>
    <column>96</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>43</line>
    <column>128</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>10</code>
    <level>2</level>
    <line>46</line>
    <column>223</column>
    <text><![CDATA[replacing unexpected </font> by </strong>]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>66</line>
    <column>104</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&city"]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>73</line>
    <column>1</column>
    <text><![CDATA[missing </strong> before <h2>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>73</line>
    <column>1</column>
    <text><![CDATA[missing </h3> before <h2>]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>74</line>
    <column>263</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>74</line>
    <column>263</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>102</line>
    <column>104</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>102</line>
    <column>257</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>102</line>
    <column>257</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>106</line>
    <column>102</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>106</line>
    <column>254</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>106</line>
    <column>254</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>110</line>
    <column>100</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>110</line>
    <column>251</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>110</line>
    <column>251</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>114</line>
    <column>98</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>114</line>
    <column>245</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>114</line>
    <column>245</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>118</line>
    <column>96</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>118</line>
    <column>242</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>118</line>
    <column>242</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>122</line>
    <column>90</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>122</line>
    <column>227</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>122</line>
    <column>227</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>126</line>
    <column>88</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>126</line>
    <column>231</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>126</line>
    <column>231</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>130</line>
    <column>90</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>130</line>
    <column>233</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>130</line>
    <column>233</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>134</line>
    <column>90</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>134</line>
    <column>236</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>134</line>
    <column>236</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>138</line>
    <column>91</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>138</line>
    <column>237</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>138</line>
    <column>237</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>142</line>
    <column>91</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>142</line>
    <column>237</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>142</line>
    <column>237</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>168</line>
    <column>132</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>168</line>
    <column>280</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>168</line>
    <column>280</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>188</line>
    <column>76</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>196</line>
    <column>153</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>200</line>
    <column>177</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>200</line>
    <column>339</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>200</line>
    <column>339</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>216</line>
    <column>90</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>4</code>
    <level>2</level>
    <line>240</line>
    <column>67</column>
    <text><![CDATA[Warning: unescaped & which should be written as &amp;]]></text>
  </message>
  <message>
    <code>66</code>
    <level>2</level>
    <line>248</line>
    <column>95</column>
    <text><![CDATA[<a> Anchor "MAP details" already defined]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>248</line>
    <column>281</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&body"]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>248</line>
    <column>281</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>296</line>
    <column>134</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>300</line>
    <column>177</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>300</line>
    <column>207</column>
    <text><![CDATA[trimming empty <font>]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>328</line>
    <column>61</column>
    <text><![CDATA[missing </a> before </h1>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>328</line>
    <column>66</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>339</line>
    <column>1</column>
    <text><![CDATA[<center> isn't allowed in <h3> elements]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>339</line>
    <column>9</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>339</line>
    <column>64</column>
    <text><![CDATA[discarding unexpected </center>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>341</line>
    <column>1</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>345</line>
    <column>2</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>349</line>
    <column>2</column>
    <text><![CDATA[<a> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>353</line>
    <column>2</column>
    <text><![CDATA[<center> isn't allowed in <h3> elements]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>353</line>
    <column>9</column>
    <text><![CDATA[missing </h3> before <h1>]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>353</line>
    <column>9</column>
    <text><![CDATA[trimming empty <h3>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>353</line>
    <column>88</column>
    <text><![CDATA[discarding unexpected </center>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>363</line>
    <column>264</column>
    <text><![CDATA[discarding unexpected </h3>]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>371</line>
    <column>79</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>7</code>
    <level>2</level>
    <line>383</line>
    <column>52</column>
    <text><![CDATA[missing </a> before </h2>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>383</line>
    <column>53</column>
    <text><![CDATA[discarding unexpected </strong>]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>383</line>
    <column>62</column>
    <text><![CDATA[discarding unexpected </a>]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>414</line>
    <column>76</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&font"]]></text>
  </message>
  <message>
    <code>3</code>
    <level>2</level>
    <line>414</line>
    <column>92</column>
    <text><![CDATA[Warning: unescaped & or unknown entity "&base"]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>414</line>
    <column>92</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>424</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected </strong>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[88 warnings, no errors were found!]]></text>
  </message>
  <message>
    <code>76</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[It is unlikely that vendor-specific, system-dependent encodings
work widely enough on the World Wide Web; you should avoid using the 
specified character encoding, instead you are recommended to
use named entities, e.g. &trade;.]]></text>
  </message>
  <message>
    <code>77</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
even if they were, they would likely be unprintable control characters.
Tidy assumed you wanted to refer to a character with the same byte value in the 
specified encoding and replaced that reference with the Unicode equivalent.]]></text>
  </message>
  <message>
    <code>78</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-8 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-8 in Annex D of ISO/IEC 10646-1:2000 also
allows for the use of five- and six-byte sequences to encode
characters that are outside the range of the Unicode character set;
those five- and six-byte sequences are illegal for the use of
UTF-8 as a transformation of Unicode characters. ISO/IEC 10646
does not allow mapping of unpaired surrogates, nor U+FFFE and U+FFFF
(but it does allow other noncharacters). For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html]]></text>
  </message>
  <message>
    <code>79</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-16 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-16 in Annex C of ISO/IEC 10646-1:2000 does not allow the
mapping of unpaired surrogates. For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html]]></text>
  </message>
  <message>
    <code>81</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[URIs must be properly escaped, they must not contain unescaped
characters below U+0021 including the space character and not
above U+007E. Tidy escapes the URI for you as recommended by
HTML 4.01 section B.2.1 and XML 1.0 section 4.2.2. Some user agents
use another algorithm to escape such URIs and some server-sided
scripts depend on that. If you want to depend on that, you must
escape the URI by your own. For more information please refer to
http://www.w3.org/International/O-URL-and-ident.html]]></text>
  </message>
  <message>
    <code>4</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The table summary attribute should be used to describe
the table structure. It is very helpful for people using
non-visual browsers. The scope and headers attributes for
table cells are useful for specifying which headers apply
to each table cell, enabling non-visual browsers to provide
a meaningful context for each cell.]]></text>
  </message>
  <message>
    <code>1</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The alt attribute should be used to give a short description
of an image; longer descriptions should be given with the
longdesc attribute which takes a URL linked to the description.
These measures are needed for people using non-graphical browsers.]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.]]></text>
  </message>
  <message>
    <code>8</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[You are recommended to use CSS to specify the font and
properties such as its size and color. This will reduce
the size of HTML files and make them easier to maintain
compared with using <FONT> elements.]]></text>
  </message>
</messages>
