<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 634889-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>21</code>
    <level>2</level>
    <line>7</line>
    <column>3</column>
    <text><![CDATA[<o:p> is not approved by W3C]]></text>
  </message>
  <message>
    <code>23</code>
    <level>2</level>
    <line>7</line>
    <column>4</column>
    <text><![CDATA[trimming empty <o:p>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML proprietary]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, no errors were found!
]]></text>
  </message>
</messages>
