<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 660397-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>17</code>
    <level>2</level>
    <line>5</line>
    <column>-3</column>
    <text><![CDATA[inserting missing 'title' element]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>7</line>
    <column>19</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>8</line>
    <column>39</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>13</line>
    <column>36</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>16</line>
    <column>12</column>
    <text><![CDATA[discarding invalid character code 99]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>17</line>
    <column>38</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>19</line>
    <column>2</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>19</line>
    <column>12</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>21</line>
    <column>50</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>23</line>
    <column>63</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>27</line>
    <column>68</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>28</line>
    <column>56</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>32</line>
    <column>18</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>34</line>
    <column>39</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>38</line>
    <column>30</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>38</line>
    <column>52</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>41</line>
    <column>36</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>41</line>
    <column>58</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>42</line>
    <column>21</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>43</line>
    <column>29</column>
    <text><![CDATA[discarding invalid character code 8e]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>43</line>
    <column>46</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>43</line>
    <column>58</column>
    <text><![CDATA[discarding invalid character code 9a]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>47</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>49</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>51</line>
    <column>38</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>51</line>
    <column>67</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>54</line>
    <column>1</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>54</line>
    <column>6</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>54</line>
    <column>29</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>55</line>
    <column>51</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>56</line>
    <column>30</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>58</line>
    <column>5</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>58</line>
    <column>60</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>59</line>
    <column>11</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>61</line>
    <column>46</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>64</line>
    <column>32</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>66</line>
    <column>43</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>68</line>
    <column>8</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>68</line>
    <column>38</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>68</line>
    <column>47</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>69</line>
    <column>54</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>70</line>
    <column>25</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>71</line>
    <column>17</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>74</line>
    <column>5</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>75</line>
    <column>34</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>75</line>
    <column>62</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>79</line>
    <column>1</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>79</line>
    <column>6</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>79</line>
    <column>22</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>80</line>
    <column>49</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>82</line>
    <column>38</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>82</line>
    <column>43</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>83</line>
    <column>47</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>84</line>
    <column>43</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>88</line>
    <column>24</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>89</line>
    <column>31</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>89</line>
    <column>63</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>92</line>
    <column>38</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>93</line>
    <column>19</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>93</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>93</line>
    <column>59</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>94</line>
    <column>29</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>96</line>
    <column>41</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>97</line>
    <column>2</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>98</line>
    <column>9</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>98</line>
    <column>19</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>98</line>
    <column>42</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>98</line>
    <column>52</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>100</line>
    <column>8</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>101</line>
    <column>55</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>102</line>
    <column>31</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>102</line>
    <column>44</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>104</line>
    <column>29</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>104</line>
    <column>45</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>109</line>
    <column>10</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>109</line>
    <column>16</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>116</line>
    <column>40</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>117</line>
    <column>16</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>117</line>
    <column>62</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>120</line>
    <column>29</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>121</line>
    <column>43</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>125</line>
    <column>45</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>126</line>
    <column>44</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>129</line>
    <column>21</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>131</line>
    <column>8</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>131</line>
    <column>47</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>132</line>
    <column>42</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>133</line>
    <column>7</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>133</line>
    <column>29</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>137</line>
    <column>29</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>138</line>
    <column>10</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>138</line>
    <column>69</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>139</line>
    <column>69</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>140</line>
    <column>43</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>141</line>
    <column>59</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>143</line>
    <column>35</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>143</line>
    <column>48</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>145</line>
    <column>32</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>149</line>
    <column>58</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>150</line>
    <column>62</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>151</line>
    <column>22</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>151</line>
    <column>66</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>152</line>
    <column>34</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>152</line>
    <column>57</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>153</line>
    <column>19</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>153</line>
    <column>35</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>155</line>
    <column>55</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>159</line>
    <column>14</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>160</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>161</line>
    <column>42</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>163</line>
    <column>51</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>164</line>
    <column>12</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>165</line>
    <column>54</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>165</line>
    <column>69</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>166</line>
    <column>54</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>167</line>
    <column>56</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>167</line>
    <column>60</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>169</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>171</line>
    <column>45</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>175</line>
    <column>32</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>178</line>
    <column>35</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>179</line>
    <column>33</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>181</line>
    <column>20</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>181</line>
    <column>26</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>182</line>
    <column>25</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>184</line>
    <column>18</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>186</line>
    <column>60</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>187</line>
    <column>40</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>187</line>
    <column>46</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>187</line>
    <column>67</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>188</line>
    <column>25</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>188</line>
    <column>53</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>189</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>191</line>
    <column>35</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>191</line>
    <column>44</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>196</line>
    <column>49</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>199</line>
    <column>14</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>199</line>
    <column>65</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>200</line>
    <column>22</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>201</line>
    <column>8</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>202</line>
    <column>20</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>203</line>
    <column>10</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>203</line>
    <column>13</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>203</line>
    <column>25</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>209</line>
    <column>66</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>212</line>
    <column>7</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>212</line>
    <column>32</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>214</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>215</line>
    <column>1</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>215</line>
    <column>33</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>218</line>
    <column>1</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>218</line>
    <column>46</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>219</line>
    <column>28</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>219</line>
    <column>42</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>222</line>
    <column>37</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>222</line>
    <column>41</column>
    <text><![CDATA[discarding invalid character code 81]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>224</line>
    <column>9</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>227</line>
    <column>35</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>231</line>
    <column>24</column>
    <text><![CDATA[discarding invalid character code 94]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>235</line>
    <column>45</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>77</code>
    <level>2</level>
    <line>237</line>
    <column>13</column>
    <text><![CDATA[discarding invalid character code 84]]></text>
  </message>
  <message>
    <code>110</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Doctype given is "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN"]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 2.0]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[161 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>76</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[It is unlikely that vendor-specific, system-dependent encodings
work widely enough on the World Wide Web; you should avoid using the 
specified character encoding, instead you are recommended to
use named entities, e.g. &trade;.
]]></text>
  </message>
  <message>
    <code>77</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
even if they were, they would likely be unprintable control characters.
Tidy assumed you wanted to refer to a character with the same byte value in the 
specified encoding and replaced that reference with the Unicode equivalent.
]]></text>
  </message>
  <message>
    <code>78</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-8 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-8 in Annex D of ISO/IEC 10646-1:2000 also
allows for the use of five- and six-byte sequences to encode
characters that are outside the range of the Unicode character set;
those five- and six-byte sequences are illegal for the use of
UTF-8 as a transformation of Unicode characters. ISO/IEC 10646
does not allow mapping of unpaired surrogates, nor U+FFFE and U+FFFF
(but it does allow other noncharacters). For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html
]]></text>
  </message>
  <message>
    <code>79</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-16 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-16 in Annex C of ISO/IEC 10646-1:2000 does not allow the
mapping of unpaired surrogates. For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html
]]></text>
  </message>
  <message>
    <code>81</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[URIs must be properly escaped, they must not contain unescaped
characters below U+0021 including the space character and not
above U+007E. Tidy escapes the URI for you as recommended by
HTML 4.01 section B.2.1 and XML 1.0 section 4.2.2. Some user agents
use another algorithm to escape such URIs and some server-sided
scripts depend on that. If you want to depend on that, you must
escape the URI by your own. For more information please refer to
http://www.w3.org/International/O-URL-and-ident.html
]]></text>
  </message>
</messages>
