<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 663548-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>32</code>
    <level>2</level>
    <line>16</line>
    <column>4</column>
    <text><![CDATA['<' + '/' + letter not allowed here]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>17</line>
    <column>-3</column>
    <text><![CDATA[discarding unexpected </script>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01 Transitional]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, no errors were found!
]]></text>
  </message>
</messages>
