<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 676205-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>65</code>
    <level>2</level>
    <line>8</line>
    <column>3</column>
    <text><![CDATA[<img> discarding newline in URI reference]]></text>
  </message>
  <message>
    <code>65</code>
    <level>2</level>
    <line>8</line>
    <column>3</column>
    <text><![CDATA[<img> discarding newline in URI reference]]></text>
  </message>
  <message>
    <code>65</code>
    <level>2</level>
    <line>8</line>
    <column>3</column>
    <text><![CDATA[<img> discarding newline in URI reference]]></text>
  </message>
  <message>
    <code>36</code>
    <level>2</level>
    <line>11</line>
    <column>1</column>
    <text><![CDATA[end of file while parsing attributes <img>]]></text>
  </message>
  <message>
    <code>64</code>
    <level>2</level>
    <line>11</line>
    <column>1</column>
    <text><![CDATA[<img> escaping malformed URI reference]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>11</line>
    <column>1</column>
    <text><![CDATA[<img> lacks "alt" attribute]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[8 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>76</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[It is unlikely that vendor-specific, system-dependent encodings
work widely enough on the World Wide Web; you should avoid using the 
specified character encoding, instead you are recommended to
use named entities, e.g. &trade;.
]]></text>
  </message>
  <message>
    <code>77</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
even if they were, they would likely be unprintable control characters.
Tidy assumed you wanted to refer to a character with the same byte value in the 
specified encoding and replaced that reference with the Unicode equivalent.
]]></text>
  </message>
  <message>
    <code>78</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-8 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-8 in Annex D of ISO/IEC 10646-1:2000 also
allows for the use of five- and six-byte sequences to encode
characters that are outside the range of the Unicode character set;
those five- and six-byte sequences are illegal for the use of
UTF-8 as a transformation of Unicode characters. ISO/IEC 10646
does not allow mapping of unpaired surrogates, nor U+FFFE and U+FFFF
(but it does allow other noncharacters). For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html
]]></text>
  </message>
  <message>
    <code>79</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[Character codes for UTF-16 must be in the range: U+0000 to U+10FFFF.
The definition of UTF-16 in Annex C of ISO/IEC 10646-1:2000 does not allow the
mapping of unpaired surrogates. For more information please refer to
http://www.unicode.org/unicode and http://www.cl.cam.ac.uk/~mgk25/unicode.html
]]></text>
  </message>
  <message>
    <code>81</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[URIs must be properly escaped, they must not contain unescaped
characters below U+0021 including the space character and not
above U+007E. Tidy escapes the URI for you as recommended by
HTML 4.01 section B.2.1 and XML 1.0 section 4.2.2. Some user agents
use another algorithm to escape such URIs and some server-sided
scripts depend on that. If you want to depend on that, you must
escape the URI by your own. For more information please refer to
http://www.w3.org/International/O-URL-and-ident.html
]]></text>
  </message>
  <message>
    <code>1</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The alt attribute should be used to give a short description
of an image; longer descriptions should be given with the
longdesc attribute which takes a URL linked to the description.
These measures are needed for people using non-graphical browsers.
]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.
]]></text>
  </message>
</messages>
