<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 763186-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>17</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[inserting missing 'title' element]]></text>
  </message>
  <message>
    <code>49</code>
    <level>2</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[<table> lacks "summary" attribute]]></text>
  </message>
  <message>
    <code>8</code>
    <level>2</level>
    <line>14</line>
    <column>1</column>
    <text><![CDATA[discarding unexpected <html>]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like HTML 4.01]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[4 warnings, no errors were found!
]]></text>
  </message>
  <message>
    <code>4</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[The table summary attribute should be used to describe
the table structure. It is very helpful for people using
non-visual browsers. The scope and headers attributes for
table cells are useful for specifying which headers apply
to each table cell, enabling non-visual browsers to provide
a meaningful context for each cell.
]]></text>
  </message>
  <message>
    <code>112</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[For further advice on how to make your pages accessible
see "http://www.w3.org/WAI/GL". You may also want to try
"http://www.cast.org/bobby/" which is a free Web-based
service for checking URLs for accessibility.
]]></text>
  </message>
</messages>
