<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- expected messages for test 788031-->
<messages>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[
Tidy (vers 4th August 2004) Parsing "InputStream"
]]></text>
  </message>
  <message>
    <code>44</code>
    <level>2</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[missing <!DOCTYPE> declaration]]></text>
  </message>
  <message>
    <code>11</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[<body> isn't allowed in <head> elements]]></text>
  </message>
  <message>
    <code>17</code>
    <level>2</level>
    <line>2</line>
    <column>1</column>
    <text><![CDATA[inserting missing 'title' element]]></text>
  </message>
  <message>
    <code>52</code>
    <level>3</level>
    <line>3</line>
    <column>1</column>
    <text><![CDATA[<body> missing '>' for end of tag]]></text>
  </message>
  <message>
    <code>111</code>
    <level>0</level>
    <line>1</line>
    <column>1</column>
    <text><![CDATA[InputStream: Document content looks like XHTML 1.0 Strict]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[3 warnings, 1 error were found!
]]></text>
  </message>
  <message>
    <code>-1</code>
    <level>0</level>
    <line>0</line>
    <column>0</column>
    <text><![CDATA[This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

]]></text>
  </message>
</messages>
